/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppOutgoingRouteImport } from './routes/_app/outgoing'
import { Route as AppLegalRouteImport } from './routes/_app/legal'
import { Route as AppIncomingRouteImport } from './routes/_app/incoming'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppActivityRouteImport } from './routes/_app/activity'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOutgoingRoute = AppOutgoingRouteImport.update({
  id: '/outgoing',
  path: '/outgoing',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomingRoute = AppIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/incoming': typeof AppIncomingRoute
  '/legal': typeof AppLegalRoute
  '/outgoing': typeof AppOutgoingRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/incoming': typeof AppIncomingRoute
  '/legal': typeof AppLegalRoute
  '/outgoing': typeof AppOutgoingRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/incoming': typeof AppIncomingRoute
  '/_app/legal': typeof AppLegalRoute
  '/_app/outgoing': typeof AppOutgoingRoute
  '/_app/reports': typeof AppReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/incoming'
    | '/legal'
    | '/outgoing'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/incoming'
    | '/legal'
    | '/outgoing'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/incoming'
    | '/_app/legal'
    | '/_app/outgoing'
    | '/_app/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outgoing': {
      id: '/_app/outgoing'
      path: '/outgoing'
      fullPath: '/outgoing'
      preLoaderRoute: typeof AppOutgoingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal': {
      id: '/_app/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incoming': {
      id: '/_app/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof AppIncomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncomingRoute: typeof AppIncomingRoute
  AppLegalRoute: typeof AppLegalRoute
  AppOutgoingRoute: typeof AppOutgoingRoute
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncomingRoute: AppIncomingRoute,
  AppLegalRoute: AppLegalRoute,
  AppOutgoingRoute: AppOutgoingRoute,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
