/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppScannerRouteImport } from './routes/_app/scanner'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProcessedTodayRouteImport } from './routes/_app/processed-today'
import { Route as AppPendingRouteImport } from './routes/_app/pending'
import { Route as AppOutgoingRouteImport } from './routes/_app/outgoing'
import { Route as AppLegalRouteImport } from './routes/_app/legal'
import { Route as AppIncomingRouteImport } from './routes/_app/incoming'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCloudRouteImport } from './routes/_app/cloud'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppActivityRouteImport } from './routes/_app/activity'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessedTodayRoute = AppProcessedTodayRouteImport.update({
  id: '/processed-today',
  path: '/processed-today',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppOutgoingRoute = AppOutgoingRouteImport.update({
  id: '/outgoing',
  path: '/outgoing',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomingRoute = AppIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCloudRoute = AppCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/assistant': typeof AppAssistantRoute
  '/cloud': typeof AppCloudRoute
  '/dashboard': typeof AppDashboardRoute
  '/incoming': typeof AppIncomingRoute
  '/legal': typeof AppLegalRoute
  '/outgoing': typeof AppOutgoingRoute
  '/pending': typeof AppPendingRoute
  '/processed-today': typeof AppProcessedTodayRoute
  '/reports': typeof AppReportsRoute
  '/scanner': typeof AppScannerRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/assistant': typeof AppAssistantRoute
  '/cloud': typeof AppCloudRoute
  '/dashboard': typeof AppDashboardRoute
  '/incoming': typeof AppIncomingRoute
  '/legal': typeof AppLegalRoute
  '/outgoing': typeof AppOutgoingRoute
  '/pending': typeof AppPendingRoute
  '/processed-today': typeof AppProcessedTodayRoute
  '/reports': typeof AppReportsRoute
  '/scanner': typeof AppScannerRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/cloud': typeof AppCloudRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/incoming': typeof AppIncomingRoute
  '/_app/legal': typeof AppLegalRoute
  '/_app/outgoing': typeof AppOutgoingRoute
  '/_app/pending': typeof AppPendingRoute
  '/_app/processed-today': typeof AppProcessedTodayRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/assistant'
    | '/cloud'
    | '/dashboard'
    | '/incoming'
    | '/legal'
    | '/outgoing'
    | '/pending'
    | '/processed-today'
    | '/reports'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/assistant'
    | '/cloud'
    | '/dashboard'
    | '/incoming'
    | '/legal'
    | '/outgoing'
    | '/pending'
    | '/processed-today'
    | '/reports'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/activity'
    | '/_app/assistant'
    | '/_app/cloud'
    | '/_app/dashboard'
    | '/_app/incoming'
    | '/_app/legal'
    | '/_app/outgoing'
    | '/_app/pending'
    | '/_app/processed-today'
    | '/_app/reports'
    | '/_app/scanner'
    | '/_app/search'
    | '/_app/settings'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processed-today': {
      id: '/_app/processed-today'
      path: '/processed-today'
      fullPath: '/processed-today'
      preLoaderRoute: typeof AppProcessedTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending': {
      id: '/_app/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outgoing': {
      id: '/_app/outgoing'
      path: '/outgoing'
      fullPath: '/outgoing'
      preLoaderRoute: typeof AppOutgoingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal': {
      id: '/_app/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incoming': {
      id: '/_app/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof AppIncomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cloud': {
      id: '/_app/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AppCloudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCloudRoute: typeof AppCloudRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncomingRoute: typeof AppIncomingRoute
  AppLegalRoute: typeof AppLegalRoute
  AppOutgoingRoute: typeof AppOutgoingRoute
  AppPendingRoute: typeof AppPendingRoute
  AppProcessedTodayRoute: typeof AppProcessedTodayRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCloudRoute: AppCloudRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncomingRoute: AppIncomingRoute,
  AppLegalRoute: AppLegalRoute,
  AppOutgoingRoute: AppOutgoingRoute,
  AppPendingRoute: AppPendingRoute,
  AppProcessedTodayRoute: AppProcessedTodayRoute,
  AppReportsRoute: AppReportsRoute,
  AppScannerRoute: AppScannerRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
